task: add support for --edit and pre-commit
KeisukeYamashita/commitlint-rs pull request #174
Opened 2023-09-21 22:31 UTC by cylewitruk

I wanted to use this together with [pre-commit](https://pre-commit.com/) but noticed that support for `--edit` was missing, so I went ahead and added at least the default using `./.git/COMMIT_EDITMSG`.

Also added a `.pre-commit-hooks.yaml` so that the repo can be used together with `pre-commit`.  Nothing fancy here...

2023-09-21 23:15 UTC, KeisukeYamashita requested changes
Thank you for your PR!
Overall LGTM, I found a typo 🙏 

I'm new to `pre-commit`, can you kindly give me any document or something about this `--edit` flag, please 🙏

2023-09-21 23:15 UTC, KeisukeYamashita commented on src/args.rs
> +                .expect("Failed to read './.git/COMMIT_EDITMSG");
```suggestion
                .expect("Failed to read './.git/COMMIT_EDITMSG'");
```

2023-09-22 06:27 UTC, KeisukeYamashita approved these changes
Thank you for your update!

2023-09-22 06:28 UTC, merged

2023-09-22 07:36 UTC, cylewitruk commented
> Thank you for your update!

No problem :)

Once you create a new release (v.0.1.3), here's an example `.pre-commit-config.yaml` which can be used with `pre-commit` in case you wanted to add it to docs :)

```yaml
default_install_hook_types: [pre-commit, commit-msg, prepare-commit-msg]
repos:
- repo: https://github.com/KeisukeYamashita/commitlint-rs
  rev: v0.1.3
  hooks:
  - id: commitlint

```

2023-10-03 03:23 UTC, KeisukeYamashita commented
@cylewitruk Sorry for the late reply 🙏 
Thanks, I'll update the doc 😄