fix invalid type 🐞
KeisukeYamashita/commitlint-rs pull request #212
Opened 2023-11-04 10:01 UTC by suyulin

# Why
commit message is "", it's panic。
commit message invalid type ,it's panic.  like this “xx”。

2023-11-04 10:11 UTC, KeisukeYamashita commented
Thank you, I'll take a look tonight!

2023-11-04 20:56 UTC, KeisukeYamashita requested changes
Thank you very much, PTAL 🙏

2023-11-04 20:56 UTC, KeisukeYamashita commented on src/rule/type.rs
> +    fn test_invalid_raw() {
```suggestion
    fn test_missing_type() {
```

2023-11-05 03:06 UTC, suyulin commented on .gitignore
> +/.idea
thx, I fixed it

2023-11-05 14:22 UTC, KeisukeYamashita approved these changes
I've updated the PR name to match or format, thank you for your contribution.
It will be shipped soon 🏃

2023-11-05 14:23 UTC, merged